name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Correct format: owner/repo@ref

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Correct format: owner/repo@ref
      with:
        node-version: '20'  # Specify the Node.js version you want

    - name: Install dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Run Code Coverage
      run: npm run coverage

    - name: Run Application
      run: npm start

    - name: Verify Application is Running
      run: curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:3000
