name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This action will be compatible with Node.js 20

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Use Node.js 20 explicitly to avoid deprecation warnings
      with:
        node-version: '20'  # Set Node.js version to 20

    - name: Install dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Run Code Coverage
      run: npm run coverage

    - name: Run Application
      run: npm start

    - name: Verify Application is Running
      run: curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:3000
